### ISSUE TITLE
Question about building rpm packge for 2.17-326.el7 on RHEL/OL8.10

### ISSUE THREAD

**Issue by woonhak** [awslabs/compat-collation-for-glibc#4]
Hi @jconway 

I'm came across this since I'm having the same issue.
In my case, we're upgrading OL7.9 to OL8.10, and seeing sort order differences and also collation versions changed.

I'm trying to build rpm package, failed to build. It's because of the latest gcc generates more warnings than older gcc.

Here's my build env.
```
$> cat /etc/os-release 
NAME="Oracle Linux Server"
VERSION="8.10"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.10"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:10:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.10
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.10

$> gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22.0.1)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$> git branch 
* 2.17-326.el7
main
```

I had multiple compilation issues related to header files(locations are different) and misconfigured autoconf/configure.
I have fixed them manually  by overriding them to have the right paths and options.
I would keep doing this, but before moving forward I'd like to confirm one thing.

Q> Do we need to build this on RHEL/OL7.9 only?
Since it's just extracted srpm package, and rebuild/compile libs,
I thought we can build this without OS version restriction as long as all the dependent libraries are available.

**Comment by jconway** [comment]
You need to **_build_** the rpm package for 2.17-326.el7 on RHEL 7, not RHEL 8. The rpm that gets built should be portable enough to install on your RHEL 8 machine.

**Comment by woonhak** [comment]
> You need to **_build_** the rpm package for 2.17-326.el7 on RHEL 7, not RHEL 8. The rpm that gets built should be portable enough to install on your RHEL 8 machine.

Thanks.

**Comment by woonhak** [comment]
Closing since it's not the real issue.
I'll build this on RHEL7 instead.
